export type APIError =
  'MISSING_REQUIRED_PARAMETER' |
  'INVALID_PARAMETER' |
  'UNAUTHORIZED_ERROR' |
  'INTERNAL_SERVER_ERROR' |
  'FORBIDDEN_ACCESST' |

  'ITEM_NOT_FOUND' |

  'UNEXPECTED_ERROR'

export type ErrorCode = APIError
