export type ErrorCode =
  // 400
  'MISSING_REQUIRED_PARAMETER' |
  'INVALID_PARAMETER' |
  // 401
  'UNAUTHORIZED_ERROR' |
  // 404
  'NOT_FOUND_ERROR' |
  // 500
  'INTERNAL_SERVER_ERROR' |
  'ASSERTION_ERROR' |
  'UNEXPECTED_ERROR'
